- app/controllers/bus_stops_controller.rb
- db/seeds.rb
> Search fail

- app/models/bus_stop.rb
- app/views/bus_stops/_form.haml
- db/migrate/20170105165853_add_timestamps_to_bus_stops.rb
- db/schema.rb
Also add completion timestamp, and mark as completed when completed is checked in form.
Closes #10.
> Add timestamps to BusStop

- config/deploy.rb
- config/deploy/production.rb
See https://github.com/umts/screaming-dinosaur/pull/94
> Don't foward agent

- app/views/bus_stops/by_route.haml
Closes #25 
This is what it looks like now
> Convert buttons to a list of links

- app/helpers/application_helper.rb
- app/helpers/bus_stops_helper.rb
> Display name

- app/controllers/bus_stops_controller.rb
- app/helpers/bus_stops_helper.rb
- app/views/bus_stops/_form.haml
- app/views/bus_stops/new.haml
- app/views/layouts/_navbar.haml
> Remove new stop page

- app/models/bus_stop.rb
- app/views/bus_stops/_form.haml
> Order stop fields

- app/views/users/edit.haml
> new header for editing user

- app/models/bus_stop.rb
- app/views/bus_stops/_form.haml
- db/migrate/20160613121307_add_full_attributes_to_bus_stops.rb
- db/migrate/20180611161343_remove_bus_stop_fields.rb
- db/migrate/20180611165044_rename_bus_stop_fields.rb
- db/migrate/20180611165148_add_bus_stop_fields.rb
- db/schema.rb
Reverts umts/stop-project#60
REVERTS THE REVERSION. Now people that matter can review
> Revert "Revert "Add missing fields and remove unused field""

- app/models/bus_stop.rb
> Add 'No sign' to mounting clearance field

- app/controllers/bus_stops_controller.rb
- app/views/bus_stops/by_route.haml
> Incomplete stops first

- app/controllers/bus_stops_controller.rb
- app/models/bus_stop.rb
- app/models/field.rb
- app/views/bus_stops/_form.haml
- db/seeds.rb
- lib/tasks/create_bus_stop_fields.rake
How does this seem as a way of setting up the edit page?
*Should merge* once approved, as the base is `rewrite`. Then the final step is the controller.
> Rewrite edit view

- app/controllers/bus_stops_controller.rb
- app/models/bus_stop.rb
- app/views/bus_stops/by_route.haml
> Pending status

- app/models/bus_stop.rb
- app/views/bus_stops/_form.haml
- db/migrate/20180619192351_change_busstop_field_type.rb
- db/schema.rb
Closes #37. I'm not sure this is the best way to do this. Please leave suggestions!
> Validate completion

- contrib/stops_for_stop_project.id
Addresses #98.
This is just a proposed code change. I have not tested this OIG.
> Exclude non-public stops

- contrib/stops_with_routes.id
Addresses #98.
This is just a proposed code change. I have not tested this OIG.
> Exclude non-public routes from route import OIG

- app/controllers/bus_stops_controller.rb
- coverage/.last_run.json
- spec/controllers/bus_stops_controller_spec.rb
- spec/factories/bus_stops.rb
- spec/system/index_spec.rb
In an attempt to test most of the site before rewrite/refactor
> Index specs

- app/models/bus_stops_route.rb
- lib/tasks/bus_stops_route_creation.rake
- lib/tasks/route_import.rake
Everything seems to be working. The tests pass, I did some manual checking of routes.
The only issue is that "direction" is now "0" or "1". I did not have time to add headsigns so that we could use those instead of displaying the direction, but it's better that that go in a different PR.
> Gtfs import

- lib/tasks/route_import.rake
> GTFS import routes

- app/controllers/bus_stops_controller.rb
> Replace sort_by inside of an each

- app/models/bus_stop.rb
- db/migrate/20180608191700_add_choices_to_field.rb
- db/migrate/20180614232518_drop_fields.rb
- db/schema.rb
> Fix broken migrations

- app/controllers/bus_stops_controller.rb
- db/schema.rb
> Dup stops on by status page

- app/models/bus_stop.rb
> Uniq route list

- app/controllers/bus_stops_controller.rb
Closes #132
Maybe I should do a separate method that isn't called `edit` and use that for both `edit` and `update`?
> Instantiate fields variable on update

- coverage/.last_run.json
- spec/factories/bus_stops.rb
- spec/factories/bus_stops_routes.rb
- spec/factories/routes.rb
- spec/factories/users.rb
- spec/models/bus_stops_route_spec.rb
Rather than static attributes (as part of an upgrade). Doing so exposed that someone had modified one of the models without changing the factory.
Also found a method that someone had written, tested, and renamed all in the same PR
> Modified factories to use blocks

- app/controllers/bus_stops_controller.rb
- coverage/.last_run.json
- spec/controllers/bus_stops_controller_spec.rb
- spec/spec_helper.rb
Closes #154 
Applied the change, as well as made a quick controller test for it.
Also fixed a format issue in the spec_helper that was causing unrelated tests to fail.
> Bus stop controller no method fix

- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
Also Bundler version. This should take care of the deprecation warnings from Bundler
> Upgraded capistrano/capistrano-bundler

- app/controllers/application_controller.rb
- config/initializers/new_framework_defaults_5_1.rb
- config/initializers/new_framework_defaults_5_2.rb
- coverage/.last_run.json
- spec/spec_helper.rb
Safe to toggle all of these, I think
> Toggle Rails 5.2 defaults on

- Gemfile
- Gemfile.lock
This app has no coffescript in it
> Remove coffee-rails

- Gemfile
- Gemfile.lock
- app/views/bus_stops/manage.haml
- app/views/bus_stops/outdated.haml
- app/views/users/index.haml
- spec/spec_helper.rb
- spec/system/bus_stops/managing_bus_stops_spec.rb
- spec/system/index_spec.rb
- spec/system/users/managing_users_spec.rb
Setup system tests to use rack-test, headless chrome if JS is needed.
This unearthed some actual test failures, too.
> Headless tests

- config/initializers/content_security_policy.rb
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
> Enable CSP headers

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
Unused as far as I can tell. I mean, this app only has 15 lines of javascript, total.
> Remove underscore

- config/environments/production.rb
We've had a few vulnerability scans really blow up our inboxes. Seems like here would be a good place to see how this setting works in practice.
> Let's try out exception grouping

- .travis.yml
- config/database.travis.yml
- config/database.yml.example
- db/migrate/20230710133909_normalize_charsets_and_collations.rb
- db/schema.rb
Also, removed username and password from example database config.
> Normalize database encoding to utf8mb4

- Gemfile
- Gemfile.lock
Also updated same and Capybara. Fixes Travis builds now that Chrome 115+ is out.
> Switch to using selenium-webdriver over webdrivers

- app/assets/javascripts/application.js
- app/assets/javascripts/bus_stops.js
- app/views/bus_stops/outdated.haml
- spec/system/bus_stops/outdated_bus_stops_spec.rb
There's just one date field in the app, just use a date field.
> Remove datepicker

- app/views/bus_stops/by_sequence.html.haml
- app/views/bus_stops/by_status.html.haml
- app/views/bus_stops/edit.html.haml
- app/views/bus_stops/field_guide.html.haml
- app/views/bus_stops/index.html.haml
- app/views/bus_stops/outdated.html.haml
- app/views/devise/registrations/edit.html.haml
- app/views/devise/sessions/new.html.haml
- app/views/users/edit.html.haml
- app/views/users/index.html.haml
- app/views/users/new.html.haml
I have a plan to get rid of the huge fonts on this site, and this will make things a bit nicer when I do.
> Make page titles h1 tags

- db/seeds.rb
`password` ain't a good password
Closes #257
> Use factorybot for user seeds

- app/assets/stylesheets/application.scss
- app/assets/stylesheets/bus_stops/edit.scss
- app/assets/stylesheets/navbar.css
- app/assets/stylesheets/scaffolds.css
- app/views/bus_stops/_form.html.haml
- app/views/bus_stops/index.html.haml
And fixed up the sizes of some other form elements.
> Get rid of huge font sizes

- app/assets/stylesheets/navbar.css
- app/helpers/application_helper.rb
- app/views/layouts/_navbar.html.haml
* Gid rid of colors, we can put them back via the better Sass variables in 4
* Stop having buttons _in_ links
* Added handling for the current page
At some point it might be nice to get the collapse working, but we don't have any of Bootstrap's JS currently.
> Pare down navbar customization

- app/javascript/application.js
- app/views/layouts/_navbar.html.haml
- app/views/layouts/application.html.haml
- config/importmap.rb
- config/initializers/assets.rb
And enable navbar collapsing and dismiss-able alerts
> Add Bootstrap JS

- app/models/bus_stop.rb
- lib/tasks/sign_type_update.rake
> Replace other with no sign

- .rubocop.yml
- Gemfile
- Gemfile.lock
- spec/factories/bus_stops_routes.rb
- spec/support/current_user.rb
> Add rubocop-factory_bot

- .haml-lint.yml
- Gemfile
- Gemfile.lock
- app/views/bus_stops/_autocomplete.html.haml
- app/views/bus_stops/_form.html.haml
- app/views/bus_stops/edit.html.haml
- app/views/bus_stops/index.html.haml
- app/views/bus_stops/manage.html.haml
- app/views/bus_stops/outdated.html.haml
- app/views/devise/shared/_error_messages.html.haml
- app/views/kaminari/_first_page.html.haml
- app/views/kaminari/_gap.html.haml
- app/views/kaminari/_last_page.html.haml
- app/views/kaminari/_next_page.html.haml
- app/views/kaminari/_prev_page.html.haml
- app/views/users/index.html.haml
And ran a first auto-correct pass
> Add haml-lint

- Gemfile
- Gemfile.lock
csv is moving from a default gem to a bundled gem in 3.4
> Add csv to Gemfile

- config/initializers/new_framework_defaults_7_2.rb
> Enable yjit
